// СГЕНЕРИРОВАНО _scrape_gems_ru_en.mjs из poe2db.tw (2026-09-29):
// /ru/Skill_Gems + /ru/Support_Gems. RU-имя гема <-> EN-имя (EN = слаг poe2db).
// Не редактировать руками — перегенерировать скриптом.
export interface GemRuEn { ru: string; en: string; kind: 'active' | 'support' }
export const GEMS_RU_EN: GemRuEn[] = [
  { ru: "[DNT] Crushing Earth", en: "DNT Crushing Earth", kind: 'active' },
  { ru: "Апокалипсис", en: "Apocalypse", kind: 'active' },
  { ru: "Арктический вой", en: "Arctic Howl", kind: 'active' },
  { ru: "Артиллерийская баллиста", en: "Artillery Ballista", kind: 'active' },
  { ru: "Архимаг", en: "Archmage", kind: 'active' },
  { ru: "Архонт Чаюлы", en: "Archon of Chayula", kind: 'active' },
  { ru: "Багровый пир", en: "Sanguine Revelry", kind: 'active' },
  { ru: "Барьер добродетели", en: "Virtuous Barrier", kind: 'active' },
  { ru: "Барьерные приспешники", en: "Wardbound Minions", kind: 'active' },
  { ru: "Беззащитность", en: "Vulnerability", kind: 'active' },
  { ru: "Берсерк", en: "Berserk", kind: 'active' },
  { ru: "Богохульство", en: "Blasphemy", kind: 'active' },
  { ru: "Боевое бешенство", en: "Combat Frenzy", kind: 'active' },
  { ru: "Болты вечной мерзлоты", en: "Permafrost Bolts", kind: 'active' },
  { ru: "Бронебойные снаряды", en: "Armour Piercing Rounds", kind: 'active' },
  { ru: "Бросок", en: "Pounce", kind: 'active' },
  { ru: "Бросок копья", en: "Spear Throw", kind: 'active' },
  { ru: "Буйное стадо", en: "Vivid Stampede", kind: 'active' },
  { ru: "Буйство", en: "Rampage", kind: 'active' },
  { ru: "Буря костей", en: "Bonestorm", kind: 'active' },
  { ru: "Буря маны", en: "Mana Tempest", kind: 'active' },
  { ru: "Быстрый выстрел", en: "Rapid Shot", kind: 'active' },
  { ru: "Веризиевые проявления", en: "Verisium Manifestations", kind: 'active' },
  { ru: "Вершина мощи", en: "Pinnacle of Power", kind: 'active' },
  { ru: "Вестник грома", en: "Herald of Thunder", kind: 'active' },
  { ru: "Вестник крови", en: "Herald of Blood", kind: 'active' },
  { ru: "Вестник льда", en: "Herald of Ice", kind: 'active' },
  { ru: "Вестник пепла", en: "Herald of Ash", kind: 'active' },
  { ru: "Вестник чумы", en: "Herald of Plague", kind: 'active' },
  { ru: "Вечная ярость", en: "Eternal Rage", kind: 'active' },
  { ru: "Вечный марш", en: "Eternal March", kind: 'active' },
  { ru: "Взмах крыльев", en: "Wing Blast", kind: 'active' },
  { ru: "Взрыв порчи", en: "Hexblast", kind: 'active' },
  { ru: "Взрыв чёрного пороха", en: "Black Powder Blitz", kind: 'active' },
  { ru: "Взрывная агония", en: "Detonate Living", kind: 'active' },
  { ru: "Взрывная болотная жаба", en: "Bursting Fen Toad", kind: 'active' },
  { ru: "Взрывная граната", en: "Explosive Grenade", kind: 'active' },
  { ru: "Взрывная смесь", en: "Explosive Concoction", kind: 'active' },
  { ru: "Взрывная стрела", en: "Detonating Arrow", kind: 'active' },
  { ru: "Взрывное копьё", en: "Explosive Spear", kind: 'active' },
  { ru: "Взрывное преображение", en: "Explosive Transmutation", kind: 'active' },
  { ru: "Взрывной выстрел", en: "Explosive Shot", kind: 'active' },
  { ru: "Вихревое копьё", en: "Whirlwind Lance", kind: 'active' },
  { ru: "Вихревой налёт", en: "Whirling Assault", kind: 'active' },
  { ru: "Вихревой удар", en: "Whirling Slash", kind: 'active' },
  { ru: "Вихрь стрел", en: "Tornado Shot", kind: 'active' },
  { ru: "Внезапный удар", en: "Flicker Strike", kind: 'active' },
  { ru: "Волк азмири", en: "Azmerian Wolf", kind: 'active' },
  { ru: "Волна мороза", en: "Wave of Frost", kind: 'active' },
  { ru: "Волчья стая", en: "Wolf Pack", kind: 'active' },
  { ru: "Воплощение безудержности", en: "Unbound Avatar", kind: 'active' },
  { ru: "Ворон тумана", en: "Mist Raven", kind: 'active' },
  { ru: "Временная иллюзия", en: "Lingering Illusion", kind: 'active' },
  { ru: "Временной разрыв", en: "Temporal Rift", kind: 'active' },
  { ru: "Всплеск Близнецов", en: "Gemini Surge", kind: 'active' },
  { ru: "Всплеск стихии", en: "Elemental Surge", kind: 'active' },
  { ru: "Всплеск хаоса", en: "Chaotic Surge", kind: 'active' },
  { ru: "Вулкан", en: "Volcano", kind: 'active' },
  { ru: "Вулканический разлом", en: "Volcanic Fissure", kind: 'active' },
  { ru: "Вызов барьера", en: "Barrier Invocation", kind: 'active' },
  { ru: "Вызов дикости", en: "Feral Invocation", kind: 'active' },
  { ru: "Вызов жнеца", en: "Reapers Invocation", kind: 'active' },
  { ru: "Вызов стихии", en: "Elemental Invocation", kind: 'active' },
  { ru: "Выпад", en: "Rake", kind: 'active' },
  { ru: "Высвобождение", en: "Unleash", kind: 'active' },
  { ru: "Высокоскоростные снаряды", en: "High Velocity Rounds", kind: 'active' },
  { ru: "Выстрел из лука", en: "Bow Shot", kind: 'active' },
  { ru: "Выстрел из самострела", en: "Crossbow Shot", kind: 'active' },
  { ru: "Выстрел с отскоком", en: "Escape Shot", kind: 'active' },
  { ru: "Вытягивание маны", en: "Mana Drain", kind: 'active' },
  { ru: "Вытягивание стихий", en: "Siphon Elements", kind: 'active' },
  { ru: "Вытягивающий удар", en: "Siphoning Strike", kind: 'active' },
  { ru: "Выход стихии", en: "Elemental Expression", kind: 'active' },
  { ru: "Вьющийся заговор", en: "Spiraling Conspiracy", kind: 'active' },
  { ru: "Газовая граната", en: "Gas Grenade", kind: 'active' },
  { ru: "Газовая стрела", en: "Gas Arrow", kind: 'active' },
  { ru: "Глашатай царицы", en: "Herald of the Royal Queen", kind: 'active' },
  { ru: "Гнев бога грома", en: "Thundergods Wrath", kind: 'active' },
  { ru: "Горючесть", en: "Flammability", kind: 'active' },
  { ru: "Град снарядов", en: "Hailstorm Rounds", kind: 'active' },
  { ru: "Гремучая смесь", en: "Fulminating Concoction", kind: 'active' },
  { ru: "Гроза", en: "Thunderstorm", kind: 'active' },
  { ru: "Грозовой переход", en: "Lightning Warp", kind: 'active' },
  { ru: "Грозовой скачок", en: "Thunderous Leap", kind: 'active' },
  { ru: "Громовая метка", en: "Voltaic Mark", kind: 'active' },
  { ru: "Громоотвод", en: "Lightning Rod", kind: 'active' },
  { ru: "Громы и молнии", en: "Fulmination", kind: 'active' },
  { ru: "Грядущая буря", en: "Gathering Storm", kind: 'active' },
  { ru: "Дар алхимика", en: "Alchemists Boon", kind: 'active' },
  { ru: "Дары Диколесья", en: "Wildwoods Gifts", kind: 'active' },
  { ru: "Дикая ярость", en: "Savage Fury", kind: 'active' },
  { ru: "Дикий защитник", en: "Wild Protector", kind: 'active' },
  { ru: "Дисциплина", en: "Discipline", kind: 'active' },
  { ru: "Длань Чаюлы", en: "Hand of Chayula", kind: 'active' },
  { ru: "Добивание слабых", en: "Cull The Weak", kind: 'active' },
  { ru: "Договор Бездны", en: "Abyssal Pact", kind: 'active' },
  { ru: "Дождь клинков", en: "Rain of Blades", kind: 'active' },
  { ru: "Дробление костей", en: "Boneshatter", kind: 'active' },
  { ru: "Дубовая кожа", en: "Barkskin", kind: 'active' },
  { ru: "Духи предков", en: "Ancestral Spirits", kind: 'active' },
  { ru: "Ездовой роа", en: "Rhoa Mount", kind: 'active' },
  { ru: "Железный барьер", en: "Iron Ward", kind: 'active' },
  { ru: "Живая бомба", en: "Living Bomb", kind: 'active' },
  { ru: "Закалка", en: "Temper Weapon", kind: 'active' },
  { ru: "Заключение в нефрите", en: "Encase in Jade", kind: 'active' },
  { ru: "Замораживающий залп", en: "Freezing Salvo", kind: 'active' },
  { ru: "Заряженный посох", en: "Charged Staff", kind: 'active' },
  { ru: "Звёздный вердикт", en: "The Stars Answer", kind: 'active' },
  { ru: "Звёздный прорыв", en: "Starborn Onslaught", kind: 'active' },
  { ru: "Землетрясение", en: "Earthquake", kind: 'active' },
  { ru: "Зенит полуночи", en: "Midnight Zenith", kind: 'active' },
  { ru: "Злословие Келари", en: "Kelaris Malediction", kind: 'active' },
  { ru: "Злость", en: "Malice", kind: 'active' },
  { ru: "Знамя войны", en: "War Banner", kind: 'active' },
  { ru: "Знамя непокорности", en: "Defiance Banner", kind: 'active' },
  { ru: "Знамя страха", en: "Dread Banner", kind: 'active' },
  { ru: "Измор", en: "Attrition", kind: 'active' },
  { ru: "Изнуряющее кольцо", en: "Enervating Nova", kind: 'active' },
  { ru: "Иллюзия пустоты", en: "Void Illusion", kind: 'active' },
  { ru: "Инфекция", en: "Contagion", kind: 'active' },
  { ru: "Искра", en: "Spark", kind: 'active' },
  { ru: "Искрящаяся ладонь", en: "Crackling Palm", kind: 'active' },
  { ru: "Испепеление", en: "Incinerate", kind: 'active' },
  { ru: "Истощающее присутствие", en: "Withering Presence", kind: 'active' },
  { ru: "Каскад Трискелиона", en: "Triskelion Cascade", kind: 'active' },
  { ru: "Келари, Порочные пески", en: "Kelari, the Tainted Sands", kind: 'active' },
  { ru: "Кипящая кровь", en: "Blood Boil", kind: 'active' },
  { ru: "Кислотная смесь", en: "Acidic Concoction", kind: 'active' },
  { ru: "Кластерная граната", en: "Cluster Grenade", kind: 'active' },
  { ru: "Клич предков", en: "Ancestral Cry", kind: 'active' },
  { ru: "Клич преисподней", en: "Infernal Cry", kind: 'active' },
  { ru: "Колдующий тотем", en: "Spell Totem", kind: 'active' },
  { ru: "Колодец Навиры", en: "Naviras Well", kind: 'active' },
  { ru: "Колокол бури", en: "Tempest Bell", kind: 'active' },
  { ru: "Кольцо льда", en: "Ice Nova", kind: 'active' },
  { ru: "Кольцо морозного пламени", en: "Frostflame Nova", kind: 'active' },
  { ru: "Колючие кусты", en: "Briarpatch", kind: 'active' },
  { ru: "Комета", en: "Comet", kind: 'active' },
  { ru: "Компаньон: {0}", en: "Companion: {0}", kind: 'active' },
  { ru: "Копьё молнии", en: "Lightning Spear", kind: 'active' },
  { ru: "Копьё Солярис", en: "Spear of Solaris", kind: 'active' },
  { ru: "Костяная клетка", en: "Bone Cage", kind: 'active' },
  { ru: "Костяной взрыв", en: "Bone Blast", kind: 'active' },
  { ru: "Крестовой удар", en: "Cross Slash", kind: 'active' },
  { ru: "Кровавая жатва", en: "Reap", kind: 'active' },
  { ru: "Кровавая охота", en: "Blood Hunt", kind: 'active' },
  { ru: "Кровопускающая смесь", en: "Bleeding Concoction", kind: 'active' },
  { ru: "Крутящий удар", en: "Rolling Slam", kind: 'active' },
  { ru: "Леденящее копьё", en: "Glacial Lance", kind: 'active' },
  { ru: "Леденящий болт", en: "Glacial Bolt", kind: 'active' },
  { ru: "Ледяное сердце", en: "Heart of Ice", kind: 'active' },
  { ru: "Ледяной выстрел", en: "Ice Shot", kind: 'active' },
  { ru: "Ледяной каскад", en: "Glacial Cascade", kind: 'active' },
  { ru: "Ледяной удар", en: "Ice Strike", kind: 'active' },
  { ru: "Ледяной шторм", en: "Icestorm", kind: 'active' },
  { ru: "Ледяные клыки", en: "Fangs of Frost", kind: 'active' },
  { ru: "Ледяные осколки", en: "Ice Shards", kind: 'active' },
  { ru: "Ливень стрел", en: "Rain of Arrows", kind: 'active' },
  { ru: "Ловушка Ружана", en: "Ruzhans Trap", kind: 'active' },
  { ru: "Лунное благословение", en: "Lunar Blessing", kind: 'active' },
  { ru: "Лунное нападение", en: "Lunar Assault", kind: 'active' },
  { ru: "Льдистые стрелы", en: "Ice-Tipped Arrows", kind: 'active' },
  { ru: "Магматический барьер", en: "Magma Barrier", kind: 'active' },
  { ru: "Магмовый взрыв", en: "Molten Blast", kind: 'active' },
  { ru: "Магнетический залп", en: "Magnetic Salvo", kind: 'active' },
  { ru: "Мантра разрушения", en: "Mantra of Destruction", kind: 'active' },
  { ru: "Масляная граната", en: "Oil Grenade", kind: 'active' },
  { ru: "Масляная очередь", en: "Oil Barrage", kind: 'active' },
  { ru: "Медитация", en: "Meditate", kind: 'active' },
  { ru: "Метка кровавой гончей", en: "Bloodhounds Mark", kind: 'active' },
  { ru: "Метка снайпера", en: "Snipers Mark", kind: 'active' },
  { ru: "Молот богов", en: "Hammer of the Gods", kind: 'active' },
  { ru: "Молот кузни", en: "Forge Hammer", kind: 'active' },
  { ru: "Молотящие лианы", en: "Thrashing Vines", kind: 'active' },
  { ru: "Момент времени", en: "Time Snap", kind: 'active' },
  { ru: "Момент уязвимости", en: "Moment of Vulnerability", kind: 'active' },
  { ru: "Морозная бомба", en: "Frost Bomb", kind: 'active' },
  { ru: "Морозная метка", en: "Freezing Mark", kind: 'active' },
  { ru: "Морозные иглы", en: "Frost Darts", kind: 'active' },
  { ru: "Морозные осколки", en: "Freezing Shards", kind: 'active' },
  { ru: "Морозный шар", en: "Frostbolt", kind: 'active' },
  { ru: "Мортира", en: "Mortar Cannon", kind: 'active' },
  { ru: "Мрачные столпы", en: "Grim Pillars", kind: 'active' },
  { ru: "Мрачный пир", en: "Grim Feast", kind: 'active' },
  { ru: "Навира, Последний мираж", en: "Navira, the Last Mirage", kind: 'active' },
  { ru: "Направленная заморозка", en: "Frozen Locus", kind: 'active' },
  { ru: "Наскок", en: "Leap Slam", kind: 'active' },
  { ru: "Натиск", en: "Stampede", kind: 'active' },
  { ru: "Натиск Валако", en: "Valakos Charge", kind: 'active' },
  { ru: "Неизбежная агония", en: "Inevitable Agony", kind: 'active' },
  { ru: "Неистовые духи", en: "Raging Spirits", kind: 'active' },
  { ru: "Нестабильный труп", en: "Volatile Dead", kind: 'active' },
  { ru: "Нечестивый ритуал", en: "Profane Ritual", kind: 'active' },
  { ru: "Носитель чумы", en: "Plague Bearer", kind: 'active' },
  { ru: "Оазис Навиры", en: "Naviras Oasis", kind: 'active' },
  { ru: "Обескровливание", en: "Exsanguinate", kind: 'active' },
  { ru: "Обман Келари", en: "Kelaris Deception", kind: 'active' },
  { ru: "Обмен анимой", en: "Animus Exchange", kind: 'active' },
  { ru: "Обморожение", en: "Hypothermia", kind: 'active' },
  { ru: "Оглушающая длань", en: "Staggering Palm", kind: 'active' },
  { ru: "Огневая поддержка", en: "Supporting Fire", kind: 'active' },
  { ru: "Огненный снаряд", en: "Firebolt", kind: 'active' },
  { ru: "Огненный шар", en: "Fireball", kind: 'active' },
  { ru: "Огненный шторм", en: "Firestorm", kind: 'active' },
  { ru: "Оздоровление", en: "Convalescence", kind: 'active' },
  { ru: "Око зимы", en: "Eye of Winter", kind: 'active' },
  { ru: "Оплетение", en: "Entangle", kind: 'active' },
  { ru: "Осадная баллиста", en: "Siege Ballista", kind: 'active' },
  { ru: "Осадный залп", en: "Siege Cascade", kind: 'active' },
  { ru: "Освящение", en: "Consecrate", kind: 'active' },
  { ru: "Осколки анимы", en: "Animus Splinters", kind: 'active' },
  { ru: "Осколочные снаряды", en: "Fragmentation Rounds", kind: 'active' },
  { ru: "Ослепляющая граната", en: "Flash Grenade", kind: 'active' },
  { ru: "Остановка времени", en: "Time Freeze", kind: 'active' },
  { ru: "Отвержение", en: "Refutation", kind: 'active' },
  { ru: "Отравляющее поле", en: "Toxic Domain", kind: 'active' },
  { ru: "Отступление", en: "Disengage", kind: 'active' },
  { ru: "Отталкивание", en: "Repulsion", kind: 'active' },
  { ru: "Отчаяние", en: "Despair", kind: 'active' },
  { ru: "Очередь", en: "Barrage", kind: 'active' },
  { ru: "Падение небес", en: "Skyfall", kind: 'active' },
  { ru: "Парирование", en: "Parry", kind: 'active' },
  { ru: "Парящая полночь", en: "Soaring Midnight", kind: 'active' },
  { ru: "Первобытные удары", en: "Primal Strikes", kind: 'active' },
  { ru: "Первобытный дар", en: "Primal Bounty", kind: 'active' },
  { ru: "Перелив энергии", en: "Power Siphon", kind: 'active' },
  { ru: "Переработанная броня", en: "Scavenged Plating", kind: 'active' },
  { ru: "Петляющие снаряды", en: "Coiling Bolts", kind: 'active' },
  { ru: "Печать силы", en: "Sigil of Power", kind: 'active' },
  { ru: "Пир плоти", en: "Feast of Flesh", kind: 'active' },
  { ru: "Питание веризием", en: "Powered by Verisium", kind: 'active' },
  { ru: "Плазменный заряд", en: "Plasma Blast", kind: 'active' },
  { ru: "Пламенное дыхание", en: "Flame Breath", kind: 'active' },
  { ru: "Пламенный взрыв", en: "Flameblast", kind: 'active' },
  { ru: "Подавляющее присутствие", en: "Overwhelming Presence", kind: 'active' },
  { ru: "Поджигающий выстрел", en: "Incendiary Shot", kind: 'active' },
  { ru: "Подношение боли", en: "Pain Offering", kind: 'active' },
  { ru: "Подношение души", en: "Soul Offering", kind: 'active' },
  { ru: "Подношение костей", en: "Bone Offering", kind: 'active' },
  { ru: "Поднятие зомби", en: "Raise Zombie", kind: 'active' },
  { ru: "Поднять щит", en: "Raise Shield", kind: 'active' },
  { ru: "Подрыв", en: "Snap", kind: 'active' },
  { ru: "Подрыв трупа", en: "Detonate Dead", kind: 'active' },
  { ru: "Пожирание", en: "Devour", kind: 'active' },
  { ru: "Поимка призрака", en: "Bind Spectre", kind: 'active' },
  { ru: "Полая концентрация", en: "Hollow Focus", kind: 'active' },
  { ru: "Полая форма", en: "Hollow Form", kind: 'active' },
  { ru: "Поле копий", en: "Spearfield", kind: 'active' },
  { ru: "Ползучая магма", en: "Rolling Magma", kind: 'active' },
  { ru: "Полый резонанс", en: "Hollow Resonance", kind: 'active' },
  { ru: "Порыв ветра", en: "Wind Blast", kind: 'active' },
  { ru: "Похищение сущности", en: "Essence Drain", kind: 'active' },
  { ru: "Праведное нисхождение", en: "Righteous Descent", kind: 'active' },
  { ru: "Предвестник безумия", en: "Harbinger of Madness", kind: 'active' },
  { ru: "Преломляющее зеркало", en: "Mirror of Refraction", kind: 'active' },
  { ru: "Призрачный лучник", en: "Mirage Archer", kind: 'active' },
  { ru: "Призрачный снайпер", en: "Mirage Deadeye", kind: 'active' },
  { ru: "Призрачный танец", en: "Ghost Dance", kind: 'active' },
  { ru: "Призыв адской гончей", en: "Summon Infernal Hound", kind: 'active' },
  { ru: "Призыв оружия", en: "Manifest Weapon", kind: 'active' },
  { ru: "Принесение в жертву", en: "Sacrifice", kind: 'active' },
  { ru: "Приручение зверя", en: "Tame Beast", kind: 'active' },
  { ru: "Приспешник скелет-воин", en: "Skeletal Warrior", kind: 'active' },
  { ru: "Прицельный выстрел", en: "Snipe", kind: 'active' },
  { ru: "Проводимость", en: "Conductivity", kind: 'active' },
  { ru: "Проводник молнии", en: "Lightning Conduit", kind: 'active' },
  { ru: "Проводящие руны", en: "Conductive Runes", kind: 'active' },
  { ru: "Прожорливый рой", en: "Ravenous Swarm", kind: 'active' },
  { ru: "Проход в Разлом", en: "Into the Breach", kind: 'active' },
  { ru: "Процессия царицы", en: "Queens Procession", kind: 'active' },
  { ru: "Прошлое и будущее", en: "Future-Past", kind: 'active' },
  { ru: "Пустая оболочка", en: "Hollow Shell", kind: 'active' },
  { ru: "Путы времени", en: "Temporal Chains", kind: 'active' },
  { ru: "Разбивающая злоба", en: "Shattering Spite", kind: 'active' },
  { ru: "Развязка", en: "Untether", kind: 'active' },
  { ru: "Раздирание", en: "Shred", kind: 'active' },
  { ru: "Разложение", en: "Decompose", kind: 'active' },
  { ru: "Разлом земли", en: "Earthshatter", kind: 'active' },
  { ru: "Разрушитель брони", en: "Armour Breaker", kind: 'active' },
  { ru: "Разрыв души", en: "Soulrend", kind: 'active' },
  { ru: "Раскалывающая длань", en: "Shattering Palm", kind: 'active' },
  { ru: "Раскалывающая смесь", en: "Shattering Concoction", kind: 'active' },
  { ru: "Раскаты грома", en: "Falling Thunder", kind: 'active' },
  { ru: "Раскол", en: "Sunder", kind: 'active' },
  { ru: "Раскол Навиры", en: "Naviras Fracturing", kind: 'active' },
  { ru: "Расплавленное сокрушение", en: "Molten Crash", kind: 'active' },
  { ru: "Расплавленный ливень", en: "Molten Shower", kind: 'active' },
  { ru: "Расплата Ружана", en: "Ruzhans Reckoning", kind: 'active' },
  { ru: "Рваная рана", en: "Rend", kind: 'active' },
  { ru: "Резонирующий щит", en: "Resonating Shield", kind: 'active' },
  { ru: "Реквием", en: "Requiem", kind: 'active' },
  { ru: "Реликты Калгуура", en: "Remnants of Kalguur", kind: 'active' },
  { ru: "Ритуал восстановления", en: "Rite of Restoration", kind: 'active' },
  { ru: "Ритуальное жертвоприношение", en: "Ritual Sacrifice", kind: 'active' },
  { ru: "Рои азмири", en: "Azmerian Swarms", kind: 'active' },
  { ru: "Ружан, Пылающий меч", en: "Ruzhan, the Blazing Sword", kind: 'active' },
  { ru: "Рунная закалка", en: "Runic Tempering", kind: 'active' },
  { ru: "Рунное отведение", en: "Runic Reprieve", kind: 'active' },
  { ru: "Сверхмощный удар", en: "Supercharged Slam", kind: 'active' },
  { ru: "Свирепый рёв", en: "Ferocious Roar", kind: 'active' },
  { ru: "Сгустки жизни", en: "Life Remnants", kind: 'active' },
  { ru: "Сгустки маны", en: "Mana Remnants", kind: 'active' },
  { ru: "Северная броня", en: "Arctic Armour", kind: 'active' },
  { ru: "Сейсмический клич", en: "Seismic Cry", kind: 'active' },
  { ru: "Силовые линии", en: "Leylines", kind: 'active' },
  { ru: "Скачок", en: "Blink", kind: 'active' },
  { ru: "Скелет-громила", en: "Skeletal Brute", kind: 'active' },
  { ru: "Скелет-клерик", en: "Skeletal Cleric", kind: 'active' },
  { ru: "Скелет-маг льда", en: "Skeletal Frost Mage", kind: 'active' },
  { ru: "Скелет-маг молний", en: "Skeletal Storm Mage", kind: 'active' },
  { ru: "Скелет-поджигатель", en: "Skeletal Arsonist", kind: 'active' },
  { ru: "Скелет-разоритель", en: "Skeletal Reaver", kind: 'active' },
  { ru: "Скелет-снайпер", en: "Skeletal Sniper", kind: 'active' },
  { ru: "Слабость", en: "Enfeeble", kind: 'active' },
  { ru: "Слияние стихий", en: "Elemental Conflux", kind: 'active' },
  { ru: "Смертельная длань", en: "Killing Palm", kind: 'active' },
  { ru: "Смерч", en: "Twister", kind: 'active' },
  { ru: "Снаряд хаоса", en: "Chaos Bolt", kind: 'active' },
  { ru: "Собиратель осколков", en: "Shard Scavenger", kind: 'active' },
  { ru: "Совершенный удар", en: "Perfect Strike", kind: 'active' },
  { ru: "Совпадение судеб", en: "Align Fate", kind: 'active' },
  { ru: "Сокрушающий страх", en: "Crushing Fear", kind: 'active' },
  { ru: "Сосуд духа", en: "Spirit Vessel", kind: 'active' },
  { ru: "Сотворение чар при блоке", en: "Cast on Block", kind: 'active' },
  { ru: "Сотворение чар при заморозке", en: "Cast on Freeze", kind: 'active' },
  { ru: "Сотворение чар при использовании оберега", en: "Cast on Charm Use", kind: 'active' },
  { ru: "Сотворение чар при критическом попадании", en: "Cast on Critical", kind: 'active' },
  { ru: "Сотворение чар при кувырке", en: "Cast on Dodge", kind: 'active' },
  { ru: "Сотворение чар при поджоге", en: "Cast on Ignite", kind: 'active' },
  { ru: "Сотворение чар при смерти приспешников", en: "Cast on Minion Death", kind: 'active' },
  { ru: "Сотворение чар при стихийном состоянии", en: "Cast on Elemental Ailment", kind: 'active' },
  { ru: "Сотворение чар при шоке", en: "Cast on Shock", kind: 'active' },
  { ru: "Сотрясающий тотем", en: "Shockwave Totem", kind: 'active' },
  { ru: "Спасение от молний", en: "Purity of Lightning", kind: 'active' },
  { ru: "Спасение от огня", en: "Purity of Fire", kind: 'active' },
  { ru: "Спасение от хаоса", en: "Impurity", kind: 'active' },
  { ru: "Спасение от холода", en: "Purity of Ice", kind: 'active' },
  { ru: "Спиральный залп", en: "Spiral Volley", kind: 'active' },
  { ru: "Стена льда", en: "Frost Wall", kind: 'active' },
  { ru: "Стена пламени", en: "Flame Wall", kind: 'active' },
  { ru: "Стена щитов", en: "Shield Wall", kind: 'active' },
  { ru: "Стихийная буря", en: "Elemental Storm", kind: 'active' },
  { ru: "Стихийный раскол", en: "Elemental Sundering", kind: 'active' },
  { ru: "Стрела лиан", en: "Vine Arrow", kind: 'active' },
  { ru: "Стрела молнии", en: "Lightning Arrow", kind: 'active' },
  { ru: "Стрела призыва бури", en: "Stormcaller Arrow", kind: 'active' },
  { ru: "Стрела цепной молнии", en: "Shockchain Arrow", kind: 'active' },
  { ru: "Стрела-проводник", en: "Electrocuting Arrow", kind: 'active' },
  { ru: "Стремительное нападение", en: "Rapid Assault", kind: 'active' },
  { ru: "Стылые трупы", en: "Bitter Dead", kind: 'active' },
  { ru: "Суд Келари", en: "Kelaris Judgment", kind: 'active' },
  { ru: "Сфера бурь", en: "Orb of Storms", kind: 'active' },
  { ru: "Сфера солнца", en: "Solar Orb", kind: 'active' },
  { ru: "Танцующий с ветром", en: "Wind Dancer", kind: 'active' },
  { ru: "Тёмное чучело", en: "Dark Effigy", kind: 'active' },
  { ru: "Тёмный договор", en: "Dark Pact", kind: 'active' },
  { ru: "Торнадо", en: "Tornado", kind: 'active' },
  { ru: "Тотем-воин предков", en: "Ancestral Warrior Totem", kind: 'active' },
  { ru: "Точные попадания", en: "Called Shots", kind: 'active' },
  { ru: "Трёпка", en: "Maul", kind: 'active' },
  { ru: "Триединство", en: "Trinity", kind: 'active' },
  { ru: "Тропа из кальтропов", en: "Trail of Caltrops", kind: 'active' },
  { ru: "Увядание", en: "Wither", kind: 'active' },
  { ru: "Удар", en: "Punch", kind: 'active' },
  { ru: "Удар булавой", en: "Mace Strike", kind: 'active' },
  { ru: "Удар в прыжке", en: "Vaulting Impact", kind: 'active' },
  { ru: "Удар грома", en: "Lightning Bolt", kind: 'active' },
  { ru: "Удар кинжалом", en: "Dagger Stab", kind: 'active' },
  { ru: "Удар кистенем", en: "Flail Strike", kind: 'active' },
  { ru: "Удар когтями", en: "Claw Stab", kind: 'active' },
  { ru: "Удар копьём", en: "Spear Stab", kind: 'active' },
  { ru: "Удар мечом", en: "Sword Slash", kind: 'active' },
  { ru: "Удар посохом", en: "Quarterstaff Strike", kind: 'active' },
  { ru: "Удар топором", en: "Axe Slash", kind: 'active' },
  { ru: "Удар щитом", en: "Shield Charge", kind: 'active' },
  { ru: "Укрепляющий клич", en: "Fortifying Cry", kind: 'active' },
  { ru: "Управление зарядами", en: "Charge Regulation", kind: 'active' },
  { ru: "Уязвимость к стихиям", en: "Elemental Weakness", kind: 'active' },
  { ru: "Фантомная стрела", en: "Phantasmal Arrow", kind: 'active' },
  { ru: "Форма демона", en: "Demon Form", kind: 'active' },
  { ru: "Фрагменты прошлого", en: "Fragments Of The Past", kind: 'active' },
  { ru: "Ходячее бедствие", en: "Walking Calamity", kind: 'active' },
  { ru: "Хохочущие спутники", en: "Cackling Companions", kind: 'active' },
  { ru: "Цепь молний", en: "Arc", kind: 'active' },
  { ru: "Чародейский барьер", en: "Sorcery Ward", kind: 'active' },
  { ru: "Чароплёт", en: "Spellslinger", kind: 'active' },
  { ru: "Чары огня при ударе", en: "Fire Spell on Hit", kind: 'active' },
  { ru: "Час нужды", en: "Time of Need", kind: 'active' },
  { ru: "Шаровая молния", en: "Ball Lightning", kind: 'active' },
  { ru: "Шквал бури", en: "Tempest Flurry", kind: 'active' },
  { ru: "Штормовая волна", en: "Storm Wave", kind: 'active' },
  { ru: "Штормовое копьё", en: "Storm Lance", kind: 'active' },
  { ru: "Штормовой болт", en: "Stormblast Bolts", kind: 'active' },
  { ru: "Эксгумация", en: "Unearth", kind: 'active' },
  { ru: "Экстренная перезарядка", en: "Emergency Reload", kind: 'active' },
  { ru: "Электризующее поле", en: "Galvanic Field", kind: 'active' },
  { ru: "Электризующие осколки", en: "Galvanic Shards", kind: 'active' },
  { ru: "Электрическая граната", en: "Voltaic Grenade", kind: 'active' },
  { ru: "Электрический барьер", en: "Voltaic Barrier", kind: 'active' },
  { ru: "Электровспышечные снаряды", en: "Shockburst Rounds", kind: 'active' },
  { ru: "Ядовитая взрывная стрела", en: "Poisonburst Arrow", kind: 'active' },
  { ru: "Ядовитое цветение", en: "Toxic Growth", kind: 'active' },
  { ru: "Янтарный шквал", en: "Ember Fusillade", kind: 'active' },
  { ru: "Яростный удар", en: "Furious Slam", kind: 'active' },
  { ru: "Ярость воздушного змея", en: "Wind Serpents Fury", kind: 'active' },
  { ru: "Ярость горы", en: "Fury of the Mountain", kind: 'active' },
  { ru: "Ярость Ружана", en: "Ruzhans Fury", kind: 'active' },
  { ru: "Авангард I", en: "Vanguard I", kind: 'support' },
  { ru: "Авангард II", en: "Vanguard II", kind: 'support' },
  { ru: "Автоматическая перезарядка", en: "Auto Reload", kind: 'support' },
  { ru: "Агнец на заклание I", en: "Sacrificial Lamb I", kind: 'support' },
  { ru: "Агнец на заклание II", en: "Sacrificial Lamb II", kind: 'support' },
  { ru: "Азарт убийства", en: "Thrill of the Kill", kind: 'support' },
  { ru: "Азарт убийства II", en: "Thrill of the Kill II", kind: 'support' },
  { ru: "Амброзия", en: "Ambrosia", kind: 'support' },
  { ru: "Амброзия II", en: "Ambrosia II", kind: 'support' },
  { ru: "Астральная проекция", en: "Astral Projection", kind: 'support' },
  { ru: "Безграничная энергия I", en: "Boundless Energy I", kind: 'support' },
  { ru: "Безграничная энергия II", en: "Boundless Energy II", kind: 'support' },
  { ru: "Беззаветные останки", en: "Selfless Remnants", kind: 'support' },
  { ru: "Безмолвие Тул", en: "Tuls Stillness", kind: 'support' },
  { ru: "Безошибочная мощь", en: "Unerring Power", kind: 'support' },
  { ru: "Безумие Каома", en: "Kaoms Madness", kind: 'support' },
  { ru: "Безустанность", en: "Unabating", kind: 'support' },
  { ru: "Безысходность", en: "Desperation", kind: 'support' },
  { ru: "Беспощадность", en: "Ruthless", kind: 'support' },
  { ru: "Бесславие Зерфи", en: "Zerphis Infamy", kind: 'support' },
  { ru: "Бесстрашие", en: "Dauntless", kind: 'support' },
  { ru: "Благословение Варашты", en: "Varashtas Blessing", kind: 'support' },
  { ru: "Боезаряд", en: "Payload", kind: 'support' },
  { ru: "Бой вплотную I", en: "Close Combat I", kind: 'support' },
  { ru: "Бой вплотную II", en: "Close Combat II", kind: 'support' },
  { ru: "Бренные останки I", en: "Harmonic Remnants I", kind: 'support' },
  { ru: "Бренные останки II", en: "Harmonic Remnants II", kind: 'support' },
  { ru: "Брешь", en: "Exploit Weakness", kind: 'support' },
  { ru: "Буря Морганы", en: "Morganas Tempest", kind: 'support' },
  { ru: "Быстрое сотворение I", en: "Rapid Casting I", kind: 'support' },
  { ru: "Быстрое сотворение II", en: "Rapid Casting II", kind: 'support' },
  { ru: "Быстрое сотворение III", en: "Rapid Casting III", kind: 'support' },
  { ru: "Быстрые атаки I", en: "Rapid Attacks I", kind: 'support' },
  { ru: "Быстрые атаки II", en: "Rapid Attacks II", kind: 'support' },
  { ru: "Быстрые атаки III", en: "Rapid Attacks III", kind: 'support' },
  { ru: "Варево I", en: "Concoct I", kind: 'support' },
  { ru: "Варево II", en: "Concoct II", kind: 'support' },
  { ru: "Вбирание шока", en: "Shock Siphon", kind: 'support' },
  { ru: "Вдумчивое сотворение", en: "Considered Casting", kind: 'support' },
  { ru: "Великолепие Каты", en: "Cathas Brilliance", kind: 'support' },
  { ru: "Ветвящиеся расселины I", en: "Branching Fissures I", kind: 'support' },
  { ru: "Ветвящиеся расселины II", en: "Branching Fissures II", kind: 'support' },
  { ru: "Вечная метка", en: "Eternal Mark", kind: 'support' },
  { ru: "Вечное пламя I", en: "Eternal Flame I", kind: 'support' },
  { ru: "Вечное пламя II", en: "Eternal Flame II", kind: 'support' },
  { ru: "Вечное пламя III", en: "Eternal Flame III", kind: 'support' },
  { ru: "Вздыбленная земля I", en: "Jagged Ground I", kind: 'support' },
  { ru: "Вздыбленная земля II", en: "Jagged Ground II", kind: 'support' },
  { ru: "Взрыв брони", en: "Armour Explosion", kind: 'support' },
  { ru: "Взрыв игл", en: "Quill Burst", kind: 'support' },
  { ru: "Взрыв Хайоши", en: "Hayoxis Fulmination", kind: 'support' },
  { ru: "Власть молний", en: "Lightning Attunement", kind: 'support' },
  { ru: "Власть огня", en: "Fire Attunement", kind: 'support' },
  { ru: "Власть хаоса", en: "Chaos Attunement", kind: 'support' },
  { ru: "Власть холода", en: "Cold Attunement", kind: 'support' },
  { ru: "Возбуждение", en: "Innervate", kind: 'support' },
  { ru: "Возвышенное проклятие", en: "Heightened Curse", kind: 'support' },
  { ru: "Возвышенные заряды", en: "Heightened Charges", kind: 'support' },
  { ru: "Воздушная волна", en: "Wind Wave", kind: 'support' },
  { ru: "Воззвание", en: "Invocation", kind: 'support' },
  { ru: "Возмездие Батира", en: "Bhatairs Vengeance", kind: 'support' },
  { ru: "Возмущение I", en: "Upheaval I", kind: 'support' },
  { ru: "Возмущение II", en: "Upheaval II", kind: 'support' },
  { ru: "Воспламенение Арбитра", en: "Arbiters Ignition", kind: 'support' },
  { ru: "Восприимчивость к молнии", en: "Lightning Exposure", kind: 'support' },
  { ru: "Восприимчивость к огню", en: "Fire Exposure", kind: 'support' },
  { ru: "Восприимчивость к холоду", en: "Cold Exposure", kind: 'support' },
  { ru: "Всплеск I", en: "Upwelling I", kind: 'support' },
  { ru: "Всплеск II", en: "Upwelling II", kind: 'support' },
  { ru: "Вспышка", en: "Dazzle", kind: 'support' },
  { ru: "Вспышка маны", en: "Mana Flare", kind: 'support' },
  { ru: "Вспышка чумы", en: "Bursting Plague", kind: 'support' },
  { ru: "Второе дыхание I", en: "Second Wind I", kind: 'support' },
  { ru: "Второе дыхание II", en: "Second Wind II", kind: 'support' },
  { ru: "Второе дыхание III", en: "Second Wind III", kind: 'support' },
  { ru: "Выносливый удар I", en: "Enduring Impact I", kind: 'support' },
  { ru: "Выносливый удар II", en: "Enduring Impact II", kind: 'support' },
  { ru: "Вырывание", en: "Rip", kind: 'support' },
  { ru: "Выстрел наудачу", en: "Gambleshot", kind: 'support' },
  { ru: "Вытягивание души", en: "Soul Drain", kind: 'support' },
  { ru: "Вытягивание жизни", en: "Life Drain", kind: 'support' },
  { ru: "Вышибание", en: "Break Posture", kind: 'support' },
  { ru: "Гемокристаллы", en: "Haemocrystals", kind: 'support' },
  { ru: "Глубокая заморозка", en: "Deep Freeze", kind: 'support' },
  { ru: "Глубокие порезы I", en: "Deep Cuts I", kind: 'support' },
  { ru: "Глубокие порезы II", en: "Deep Cuts II", kind: 'support' },
  { ru: "Гнев Сионы", en: "Siones Temper", kind: 'support' },
  { ru: "Гнев Такати", en: "Tacatis Ire", kind: 'support' },
  { ru: "Голодное остервенение I", en: "Feeding Frenzy I", kind: 'support' },
  { ru: "Голодное остервенение II", en: "Feeding Frenzy II", kind: 'support' },
  { ru: "Гора Стирна", en: "Styrns Mountain", kind: 'support' },
  { ru: "Гордыня Олрота", en: "Olroths Hubris", kind: 'support' },
  { ru: "Господство Кулемака", en: "Kulemaks Dominion", kind: 'support' },
  { ru: "Гранаты-липучки I", en: "Adhesive Grenades I", kind: 'support' },
  { ru: "Гранаты-липучки II", en: "Adhesive Grenades II", kind: 'support' },
  { ru: "Гранаты-липучки III", en: "Adhesive Grenades III", kind: 'support' },
  { ru: "Грозовая цепь", en: "Stormchain", kind: 'support' },
  { ru: "Гром Эонира", en: "Eonyrs Thunder", kind: 'support' },
  { ru: "Громадные приспешники", en: "Hulking Minions", kind: 'support' },
  { ru: "Губительное прикосновение", en: "Withering Touch", kind: 'support' },
  { ru: "Дальний выстрел I", en: "Longshot I", kind: 'support' },
  { ru: "Дальний выстрел II", en: "Longshot II", kind: 'support' },
  { ru: "Дар жизни", en: "Life Bounty", kind: 'support' },
  { ru: "Дар маны", en: "Mana Bounty", kind: 'support' },
  { ru: "Два ствола I", en: "Double Barrel I", kind: 'support' },
  { ru: "Два ствола II", en: "Double Barrel II", kind: 'support' },
  { ru: "Два ствола III", en: "Double Barrel III", kind: 'support' },
  { ru: "Десятина Аманаму", en: "Amanamus Tithe", kind: 'support' },
  { ru: "Дикость", en: "Ferocity", kind: 'support' },
  { ru: "Длинный запал I", en: "Long Fuse I", kind: 'support' },
  { ru: "Длинный запал II", en: "Long Fuse II", kind: 'support' },
  { ru: "Длительный шок", en: "Lasting Shock", kind: 'support' },
  { ru: "Добивание I", en: "Culling Strike I", kind: 'support' },
  { ru: "Добивание II", en: "Culling Strike II", kind: 'support' },
  { ru: "Договор служения I", en: "Minion Pact I", kind: 'support' },
  { ru: "Договор служения II", en: "Minion Pact II", kind: 'support' },
  { ru: "Долговременная земля", en: "Lasting Ground", kind: 'support' },
  { ru: "Дрожь", en: "Tremors", kind: 'support' },
  { ru: "Едкость", en: "Acrimony", kind: 'support' },
  { ru: "Её заявление", en: "Her Declaration", kind: 'support' },
  { ru: "Жатва сущности", en: "Essence Harvest", kind: 'support' },
  { ru: "Жгучие критические удары", en: "Blazing Critical", kind: 'support' },
  { ru: "Желание Диаллы", en: "Diallas Desire", kind: 'support' },
  { ru: "Жертвенное подношение", en: "Sacrificial Offering", kind: 'support' },
  { ru: "Жертвенность", en: "Immolate", kind: 'support' },
  { ru: "Жестокость I", en: "Brutality I", kind: 'support' },
  { ru: "Жестокость II", en: "Brutality II", kind: 'support' },
  { ru: "Жестокость III", en: "Brutality III", kind: 'support' },
  { ru: "Живая молния", en: "Living Lightning", kind: 'support' },
  { ru: "Живая молния II", en: "Living Lightning II", kind: 'support' },
  { ru: "Живой щит I", en: "Meat Shield I", kind: 'support' },
  { ru: "Живой щит II", en: "Meat Shield II", kind: 'support' },
  { ru: "Живучесть I", en: "Vitality I", kind: 'support' },
  { ru: "Живучесть II", en: "Vitality II", kind: 'support' },
  { ru: "Жизнеотвод", en: "Lifetap", kind: 'support' },
  { ru: "Забота Тахоа", en: "Tawhoas Tending", kind: 'support' },
  { ru: "Задержка срабатывания", en: "Delayed Reaction", kind: 'support' },
  { ru: "Залповый огонь I", en: "Multishot I", kind: 'support' },
  { ru: "Залповый огонь II", en: "Multishot II", kind: 'support' },
  { ru: "Замедление снарядов I", en: "Projectile Deceleration I", kind: 'support' },
  { ru: "Замедление снарядов II", en: "Projectile Deceleration II", kind: 'support' },
  { ru: "Замёрзший гнев", en: "Frozen Spite", kind: 'support' },
  { ru: "Заморозка", en: "Freeze", kind: 'support' },
  { ru: "Заряженная метка", en: "Charged Mark", kind: 'support' },
  { ru: "Заряженные выстрелы I", en: "Charged Shots I", kind: 'support' },
  { ru: "Заряженные выстрелы II", en: "Charged Shots II", kind: 'support' },
  { ru: "Заряженные искры I", en: "Empowered Sparks I", kind: 'support' },
  { ru: "Заряженные искры II", en: "Empowered Sparks II", kind: 'support' },
  { ru: "Засада", en: "Ambush", kind: 'support' },
  { ru: "Зенит I", en: "Zenith I", kind: 'support' },
  { ru: "Зенит II", en: "Zenith II", kind: 'support' },
  { ru: "Знамение Утреда", en: "Uhtreds Omen", kind: 'support' },
  { ru: "Зов предков I", en: "Ancestral Call I", kind: 'support' },
  { ru: "Зов предков II", en: "Ancestral Call II", kind: 'support' },
  { ru: "Зов предков III", en: "Ancestral Call III", kind: 'support' },
  { ru: "Из холода в жар", en: "Frostfire", kind: 'support' },
  { ru: "Избыток зарядов I", en: "Charge Profusion I", kind: 'support' },
  { ru: "Избыток зарядов II", en: "Charge Profusion II", kind: 'support' },
  { ru: "Извержение вулкана", en: "Volcanic Eruption", kind: 'support' },
  { ru: "Извлечение", en: "Extraction", kind: 'support' },
  { ru: "Изматывание", en: "Enervation", kind: 'support' },
  { ru: "Изморозь", en: "Hoarfrost", kind: 'support' },
  { ru: "Ингибитор", en: "Inhibitor", kind: 'support' },
  { ru: "Иней", en: "Verglas", kind: 'support' },
  { ru: "Интенсивная агония", en: "Intense Agony", kind: 'support' },
  { ru: "Интенсивность", en: "Infusion", kind: 'support' },
  { ru: "Исключительная выносливость", en: "Perfected Endurance", kind: 'support' },
  { ru: "Искрящий барьер", en: "Crackling Barrier", kind: 'support' },
  { ru: "Искушение Атзири", en: "Atziris Allure", kind: 'support' },
  { ru: "Исход Утреда", en: "Uhtreds Exodus", kind: 'support' },
  { ru: "Исцеляющие руны", en: "Healing Runes", kind: 'support' },
  { ru: "Кадильница Тангмазу", en: "Tangmazus Thurible", kind: 'support' },
  { ru: "Казнь I", en: "Execute I", kind: 'support' },
  { ru: "Казнь II", en: "Execute II", kind: 'support' },
  { ru: "Казнь III", en: "Execute III", kind: 'support' },
  { ru: "Кальтропы", en: "Caltrops", kind: 'support' },
  { ru: "Каннибализм I", en: "Cannibalism I", kind: 'support' },
  { ru: "Каннибализм II", en: "Cannibalism II", kind: 'support' },
  { ru: "Каскад чар", en: "Spell Cascade", kind: 'support' },
  { ru: "Катализирующие стихии", en: "Catalysing Elements", kind: 'support' },
  { ru: "Катарсис", en: "Catharsis", kind: 'support' },
  { ru: "Клич восприимчивости", en: "Exposing Cry", kind: 'support' },
  { ru: "Клятва Исина", en: "Oisíns Oath", kind: 'support' },
  { ru: "Колдовской выброс", en: "Arcane Surge", kind: 'support' },
  { ru: "Кольцо снарядов I", en: "Nova Projectiles I", kind: 'support' },
  { ru: "Кольцо снарядов II", en: "Nova Projectiles II", kind: 'support' },
  { ru: "Колючки I", en: "Barbs I", kind: 'support' },
  { ru: "Колючки II", en: "Barbs II", kind: 'support' },
  { ru: "Колючки III", en: "Barbs III", kind: 'support' },
  { ru: "Компактные снаряды", en: "Streamlined Rounds", kind: 'support' },
  { ru: "Контролируемое разрушение", en: "Controlled Destruction", kind: 'support' },
  { ru: "Концентрация стихий", en: "Elemental Focus", kind: 'support' },
  { ru: "Короткий запал I", en: "Short Fuse I", kind: 'support' },
  { ru: "Короткий запал II", en: "Short Fuse II", kind: 'support' },
  { ru: "Коррозия", en: "Corrosion", kind: 'support' },
  { ru: "Костёр Ксофа", en: "Xophs Pyre", kind: 'support' },
  { ru: "Костяная шрапнель", en: "Bone Shrapnel", kind: 'support' },
  { ru: "Красный цвет", en: "See Red", kind: 'support' },
  { ru: "Кратер", en: "Crater", kind: 'support' },
  { ru: "Крепость духа", en: "Strong Hearted", kind: 'support' },
  { ru: "Крепость I", en: "Fortress I", kind: 'support' },
  { ru: "Крепость II", en: "Fortress II", kind: 'support' },
  { ru: "Крещендо Калисы", en: "Kalisas Crescendo", kind: 'support' },
  { ru: "Крещендо I", en: "Crescendo I", kind: 'support' },
  { ru: "Крещендо II", en: "Crescendo II", kind: 'support' },
  { ru: "Крещендо III", en: "Crescendo III", kind: 'support' },
  { ru: "Кристальные осколки", en: "Crystalline Shards", kind: 'support' },
  { ru: "Кровожадность", en: "Bloodlust", kind: 'support' },
  { ru: "Кровопускание Аталуи", en: "Ataluis Bloodletting", kind: 'support' },
  { ru: "Кровотечение I", en: "Bleed I", kind: 'support' },
  { ru: "Кровотечение II", en: "Bleed II", kind: 'support' },
  { ru: "Кровотечение III", en: "Bleed III", kind: 'support' },
  { ru: "Кровотечение IV", en: "Bleed IV", kind: 'support' },
  { ru: "Крушащий крик", en: "Battershout", kind: 'support' },
  { ru: "Кулак войны I", en: "Fist of War I", kind: 'support' },
  { ru: "Кулак войны II", en: "Fist of War II", kind: 'support' },
  { ru: "Кулак войны III", en: "Fist of War III", kind: 'support' },
  { ru: "Кулак Калгуура", en: "Fist Of Kalguur", kind: 'support' },
  { ru: "Кульминация I", en: "Culmination I", kind: 'support' },
  { ru: "Кульминация II", en: "Culmination II", kind: 'support' },
  { ru: "Культивация Сирэл", en: "Cirels Cultivation", kind: 'support' },
  { ru: "Купель крови", en: "Font of Blood", kind: 'support' },
  { ru: "Купель маны", en: "Font of Mana", kind: 'support' },
  { ru: "Купель свирепости", en: "Font of Rage", kind: 'support' },
  { ru: "Кусачий мороз I", en: "Biting Frost I", kind: 'support' },
  { ru: "Кусачий мороз II", en: "Biting Frost II", kind: 'support' },
  { ru: "Лавина Тул", en: "Tuls Avalanche", kind: 'support' },
  { ru: "Ледник", en: "Glacier", kind: 'support' },
  { ru: "Ловкая перезарядка", en: "Nimble Reload", kind: 'support' },
  { ru: "Магнитные останки", en: "Magnetic Remnants", kind: 'support' },
  { ru: "Марш смерти", en: "Deathmarch", kind: 'support' },
  { ru: "Мастерство молнии", en: "Lightning Mastery", kind: 'support' },
  { ru: "Мастерство огня", en: "Fire Mastery", kind: 'support' },
  { ru: "Мастерство приспешников", en: "Minion Mastery", kind: 'support' },
  { ru: "Мастерство физического урона", en: "Physical Mastery", kind: 'support' },
  { ru: "Мастерство хаоса", en: "Chaos Mastery", kind: 'support' },
  { ru: "Мастерство холода", en: "Cold Mastery", kind: 'support' },
  { ru: "Медаль Аржуна", en: "Arjuns Medal", kind: 'support' },
  { ru: "Мелодия Эйлит", en: "Ailiths Chimes", kind: 'support' },
  { ru: "Месть Текрода", en: "Tecrods Revenge", kind: 'support' },
  { ru: "Метка вытягивания", en: "Mark of Siphoning", kind: 'support' },
  { ru: "Метка вытягивания II", en: "Mark of Siphoning II", kind: 'support' },
  { ru: "Метка смерти", en: "Mark for Death", kind: 'support' },
  { ru: "Метка смерти II", en: "Mark for Death II", kind: 'support' },
  { ru: "Мистицизм I", en: "Mysticism I", kind: 'support' },
  { ru: "Мистицизм II", en: "Mysticism II", kind: 'support' },
  { ru: "Мобильность", en: "Mobility", kind: 'support' },
  { ru: "Могучее дерево II", en: "Greatwood II", kind: 'support' },
  { ru: "Мозг Изувера", en: "Brutus Brain", kind: 'support' },
  { ru: "Морозная пурга", en: "Frozen Vortex", kind: 'support' },
  { ru: "Морозное разветвление", en: "Freezefork", kind: 'support' },
  { ru: "Мощные останки III", en: "Remnant Potency III", kind: 'support' },
  { ru: "Мука Ишчейла", en: "Ixchels Torment", kind: 'support' },
  { ru: "Мятеж Зарока", en: "Zarokhs Revolt", kind: 'support' },
  { ru: "На длину руки", en: "Arms Length", kind: 'support' },
  { ru: "Набат Спящего", en: "Dreamers Knell", kind: 'support' },
  { ru: "Наведённое проклятие", en: "Focused Curse", kind: 'support' },
  { ru: "Надвигающаяся буря", en: "Advancing Storm", kind: 'support' },
  { ru: "Надир", en: "Nadir", kind: 'support' },
  { ru: "Накопитель энергии", en: "Energy Capacitor", kind: 'support' },
  { ru: "Нападение Раты", en: "Rathas Assault", kind: 'support' },
  { ru: "Нарастающий яд", en: "Escalating Poison", kind: 'support' },
  { ru: "Неизбежность Рууна", en: "Vruuns Inevitability", kind: 'support' },
  { ru: "Неистовство Медведя", en: "Medveds Felling", kind: 'support' },
  { ru: "Нейронная перегрузка", en: "Neural Overload", kind: 'support' },
  { ru: "Неослабная свирепость", en: "Relentless Rage", kind: 'support' },
  { ru: "Неотвратимые критические удары I", en: "Inexorable Critical I", kind: 'support' },
  { ru: "Неотвратимые критические удары II", en: "Inexorable Critical II", kind: 'support' },
  { ru: "Неповиновение I", en: "Defy I", kind: 'support' },
  { ru: "Неповиновение II", en: "Defy II", kind: 'support' },
  { ru: "Непреклонность", en: "Unyielding", kind: 'support' },
  { ru: "Неприкосновенность", en: "Untouchable", kind: 'support' },
  { ru: "Неровный темп", en: "Unsteady Tempo", kind: 'support' },
  { ru: "Несгибаемость", en: "Unbending", kind: 'support' },
  { ru: "Несломимость", en: "Unbreakable", kind: 'support' },
  { ru: "Нестабильная мощь", en: "Volatile Power", kind: 'support' },
  { ru: "Нестабильность", en: "Volatility", kind: 'support' },
  { ru: "Нестабильность приспешников", en: "Minion Instability", kind: 'support' },
  { ru: "Нетерпение Атзири", en: "Atziris Impatience", kind: 'support' },
  { ru: "Неутомимость", en: "Tireless", kind: 'support' },
  { ru: "Нечестивость I", en: "Profanity I", kind: 'support' },
  { ru: "Нечестивость II", en: "Profanity II", kind: 'support' },
  { ru: "Обезглавливание I", en: "Behead I", kind: 'support' },
  { ru: "Обезглавливание II", en: "Behead II", kind: 'support' },
  { ru: "Обездвиживание", en: "Lockdown", kind: 'support' },
  { ru: "Обжигающее пламя I", en: "Searing Flame I", kind: 'support' },
  { ru: "Обжигающее пламя II", en: "Searing Flame II", kind: 'support' },
  { ru: "Ободрение", en: "Rally", kind: 'support' },
  { ru: "Обречённость", en: "Impending Doom", kind: 'support' },
  { ru: "Обходной манёвр", en: "Outmaneuver", kind: 'support' },
  { ru: "Объятия Уул-Нетол", en: "Uul-Netols Embrace", kind: 'support' },
  { ru: "Оглушение I", en: "Stun I", kind: 'support' },
  { ru: "Оглушение II", en: "Stun II", kind: 'support' },
  { ru: "Оглушение III", en: "Stun III", kind: 'support' },
  { ru: "Оживление Хаталя", en: "Khatals Rejuvenation", kind: 'support' },
  { ru: "Окно возможностей I", en: "Window of Opportunity I", kind: 'support' },
  { ru: "Окно возможностей II", en: "Window of Opportunity II", kind: 'support' },
  { ru: "Осада Вораны", en: "Voranas Siege", kind: 'support' },
  { ru: "Оскверняющий клич I", en: "Corrupting Cry I", kind: 'support' },
  { ru: "Оскверняющий клич II", en: "Corrupting Cry II", kind: 'support' },
  { ru: "Осколок Плута", en: "Tricksters Shard", kind: 'support' },
  { ru: "Ослепление I", en: "Blind I", kind: 'support' },
  { ru: "Ослепление II", en: "Blind II", kind: 'support' },
  { ru: "Остаточная волна I", en: "Aftershock I", kind: 'support' },
  { ru: "Остаточная волна II", en: "Aftershock II", kind: 'support' },
  { ru: "Остаточная волна III", en: "Aftershock III", kind: 'support' },
  { ru: "Отбрасывание", en: "Knockback", kind: 'support' },
  { ru: "Отдающийся крик", en: "Echoing Cry", kind: 'support' },
  { ru: "Отложенная награда", en: "Delayed Gratification", kind: 'support' },
  { ru: "Отмщение I", en: "Retaliate I", kind: 'support' },
  { ru: "Отмщение II", en: "Retaliate II", kind: 'support' },
  { ru: "Отработанный приём", en: "Practiced Combo", kind: 'support' },
  { ru: "Отравление I", en: "Poison I", kind: 'support' },
  { ru: "Отравление II", en: "Poison II", kind: 'support' },
  { ru: "Отравление III", en: "Poison III", kind: 'support' },
  { ru: "Отсечение Гвателитзи", en: "Guatelitzis Ablation", kind: 'support' },
  { ru: "Отступление I", en: "Retreat I", kind: 'support' },
  { ru: "Отступление II", en: "Retreat II", kind: 'support' },
  { ru: "Отступление III", en: "Retreat III", kind: 'support' },
  { ru: "Отчаянный удар I", en: "Direstrike I", kind: 'support' },
  { ru: "Отчаянный удар II", en: "Direstrike II", kind: 'support' },
  { ru: "Охват", en: "Overreach", kind: 'support' },
  { ru: "Охват Арбитра", en: "Arbiters Reach", kind: 'support' },
  { ru: "Охватывающая земля", en: "Encroaching Ground", kind: 'support' },
  { ru: "Охлаждение", en: "Embitter", kind: 'support' },
  { ru: "Оцепенение", en: "Daze", kind: 'support' },
  { ru: "Оцепеняющий клич", en: "Dazing Cry", kind: 'support' },
  { ru: "Очаг холода", en: "Frost Nexus", kind: 'support' },
  { ru: "Очищающее пламя", en: "Scouring Flame", kind: 'support' },
  { ru: "Пагуба Доэдре", en: "Doedres Undoing", kind: 'support' },
  { ru: "Пакт Паквате", en: "Paquates Pact", kind: 'support' },
  { ru: "Первая кровь", en: "First Blood", kind: 'support' },
  { ru: "Первый ход", en: "Opening Move", kind: 'support' },
  { ru: "Перевес", en: "Leverage", kind: 'support' },
  { ru: "Перегрузка", en: "Overcharge", kind: 'support' },
  { ru: "Переизбыток I", en: "Overabundance I", kind: 'support' },
  { ru: "Переизбыток II", en: "Overabundance II", kind: 'support' },
  { ru: "Переизбыток III", en: "Overabundance III", kind: 'support' },
  { ru: "Перенапряжение", en: "Overextend", kind: 'support' },
  { ru: "Песочные часы", en: "Hourglass", kind: 'support' },
  { ru: "Плавильня Урука", en: "Uruks Smelting", kind: 'support' },
  { ru: "Пламенная смерть", en: "Fiery Death", kind: 'support' },
  { ru: "Пламя бури", en: "Stormfire", kind: 'support' },
  { ru: "Пляска смерти", en: "Danse Macabre", kind: 'support' },
  { ru: "Повеление", en: "Commandment", kind: 'support' },
  { ru: "Поводок Каргала", en: "Kurgals Leash", kind: 'support' },
  { ru: "Повторное взведение I", en: "Rearm I", kind: 'support' },
  { ru: "Повторное взведение II", en: "Rearm II", kind: 'support' },
  { ru: "Повышенная меткость I", en: "Heightened Accuracy I", kind: 'support' },
  { ru: "Повышенная меткость II", en: "Heightened Accuracy II", kind: 'support' },
  { ru: "Поглощение состояний", en: "Drain Ailments", kind: 'support' },
  { ru: "Погоня I", en: "Pursuit I", kind: 'support' },
  { ru: "Погоня II", en: "Pursuit II", kind: 'support' },
  { ru: "Погоня III", en: "Pursuit III", kind: 'support' },
  { ru: "Поджог I", en: "Ignite I", kind: 'support' },
  { ru: "Поджог II", en: "Ignite II", kind: 'support' },
  { ru: "Поджог III", en: "Ignite III", kind: 'support' },
  { ru: "Поднимающийся шквал", en: "Rising Tempest", kind: 'support' },
  { ru: "Подсечка", en: "Undermine", kind: 'support' },
  { ru: "Подчиняющая порча", en: "Abiding Hex", kind: 'support' },
  { ru: "Пожар", en: "Wildfire", kind: 'support' },
  { ru: "Ползучий хлад", en: "Creeping Chill", kind: 'support' },
  { ru: "Помощь предков", en: "Ancestral Aid", kind: 'support' },
  { ru: "Порог I", en: "Brink I", kind: 'support' },
  { ru: "Порог II", en: "Brink II", kind: 'support' },
  { ru: "Последний вздох", en: "Last Gasp", kind: 'support' },
  { ru: "Последствие Рууна", en: "Vruuns Aftermath", kind: 'support' },
  { ru: "Постоянная земля I", en: "Persistent Ground I", kind: 'support' },
  { ru: "Постоянная земля II", en: "Persistent Ground II", kind: 'support' },
  { ru: "Постоянная земля III", en: "Persistent Ground III", kind: 'support' },
  { ru: "Постоянный заряд", en: "Perpetual Charge", kind: 'support' },
  { ru: "Потенциал", en: "Potential", kind: 'support' },
  { ru: "Поток", en: "Flow", kind: 'support' },
  { ru: "Поток Ракиаты", en: "Rakiatas Flow", kind: 'support' },
  { ru: "Похищение здоровья I", en: "Life Leech I", kind: 'support' },
  { ru: "Похищение здоровья II", en: "Life Leech II", kind: 'support' },
  { ru: "Похищение здоровья III", en: "Life Leech III", kind: 'support' },
  { ru: "Похищение маны", en: "Mana Leech", kind: 'support' },
  { ru: "Похоть Аракаали", en: "Arakaalis Lust", kind: 'support' },
  { ru: "Практическая магия I", en: "Practical Magic I", kind: 'support' },
  { ru: "Практическая магия II", en: "Practical Magic II", kind: 'support' },
  { ru: "Преданность", en: "Loyalty", kind: 'support' },
  { ru: "Предумышленность", en: "Premeditation", kind: 'support' },
  { ru: "Предчувствие Утреда", en: "Uhtreds Augury", kind: 'support' },
  { ru: "Преломление I", en: "Refraction I", kind: 'support' },
  { ru: "Преломление II", en: "Refraction II", kind: 'support' },
  { ru: "Преломление III", en: "Refraction III", kind: 'support' },
  { ru: "Пресыщение", en: "Gorge", kind: 'support' },
  { ru: "Пригвождение I", en: "Pin I", kind: 'support' },
  { ru: "Пригвождение II", en: "Pin II", kind: 'support' },
  { ru: "Пригвождение III", en: "Pin III", kind: 'support' },
  { ru: "Призрачный залп", en: "Spectral Volley", kind: 'support' },
  { ru: "Призыв Атзири", en: "Atziris Call", kind: 'support' },
  { ru: "Приказание I", en: "Bidding I", kind: 'support' },
  { ru: "Приказание II", en: "Bidding II", kind: 'support' },
  { ru: "Приказание III", en: "Bidding III", kind: 'support' },
  { ru: "Примесь", en: "Admixture", kind: 'support' },
  { ru: "Причастие Атзири", en: "Atziris Communion", kind: 'support' },
  { ru: "Проводник шока", en: "Shock Conduction", kind: 'support' },
  { ru: "Проводник шока II", en: "Shock Conduction II", kind: 'support' },
  { ru: "Продление I", en: "Prolonged Duration I", kind: 'support' },
  { ru: "Продление II", en: "Prolonged Duration II", kind: 'support' },
  { ru: "Продление III", en: "Prolonged Duration III", kind: 'support' },
  { ru: "Проклятая земля", en: "Cursed Ground", kind: 'support' },
  { ru: "Прокол", en: "Impale", kind: 'support' },
  { ru: "Пронзание пламени", en: "Flamepierce", kind: 'support' },
  { ru: "Пронзание I", en: "Pierce I", kind: 'support' },
  { ru: "Пронзание II", en: "Pierce II", kind: 'support' },
  { ru: "Пронзание III", en: "Pierce III", kind: 'support' },
  { ru: "Пронизывающие молнии", en: "Lightning Penetration", kind: 'support' },
  { ru: "Пронизывающий жар I", en: "Fire Penetration I", kind: 'support' },
  { ru: "Пронизывающий жар II", en: "Fire Penetration II", kind: 'support' },
  { ru: "Пронизывающий холод", en: "Cold Penetration", kind: 'support' },
  { ru: "Проницательность Морриган", en: "Mórrigans Insight", kind: 'support' },
  { ru: "Прорыв", en: "Punch Through", kind: 'support' },
  { ru: "Прототип семнадцать", en: "Prototype Seventeen", kind: 'support' },
  { ru: "Прочность", en: "Durability", kind: 'support' },
  { ru: "Прочные тотемы I", en: "Hardy Totems I", kind: 'support' },
  { ru: "Прочные тотемы II", en: "Hardy Totems II", kind: 'support' },
  { ru: "Пылающее начертание", en: "Burning Inscription", kind: 'support' },
  { ru: "Пылающий легион I", en: "Infernal Legion I", kind: 'support' },
  { ru: "Пылающий легион II", en: "Infernal Legion II", kind: 'support' },
  { ru: "Пылающий легион III", en: "Infernal Legion III", kind: 'support' },
  { ru: "Разбег", en: "Momentum", kind: 'support' },
  { ru: "Разбиватель брони I", en: "Armour Demolisher I", kind: 'support' },
  { ru: "Разбиватель брони II", en: "Armour Demolisher II", kind: 'support' },
  { ru: "Разброс", en: "Fluke", kind: 'support' },
  { ru: "Разветвление", en: "Fork", kind: 'support' },
  { ru: "Разгон Виленты", en: "Vilentas Propulsion", kind: 'support' },
  { ru: "Разгром", en: "Devastate", kind: 'support' },
  { ru: "Разгул стужи", en: "Spreading Frost", kind: 'support' },
  { ru: "Раздувшееся пламя", en: "Fan The Flames", kind: 'support' },
  { ru: "Раздувшееся пламя II", en: "Fan The Flames II", kind: 'support' },
  { ru: "Разлагающая порча", en: "Decaying Hex", kind: 'support' },
  { ru: "Разлад", en: "Derange", kind: 'support' },
  { ru: "Разрастание I", en: "Burgeon I", kind: 'support' },
  { ru: "Разрастание II", en: "Burgeon II", kind: 'support' },
  { ru: "Разрез", en: "Incision", kind: 'support' },
  { ru: "Разрушение брони I", en: "Armour Break I", kind: 'support' },
  { ru: "Разрушение брони II", en: "Armour Break II", kind: 'support' },
  { ru: "Разрушение брони III", en: "Armour Break III", kind: 'support' },
  { ru: "Разрушитель душ", en: "Soulbreaker", kind: 'support' },
  { ru: "Разрушительная выносливость", en: "Break Endurance", kind: 'support' },
  { ru: "Разрушительный финал", en: "Rending Apex", kind: 'support' },
  { ru: "Разрыв", en: "Tear", kind: 'support' },
  { ru: "Разрыв повелителя Разлома", en: "Breachlords Rift", kind: 'support' },
  { ru: "Разрывание", en: "Rupture", kind: 'support' },
  { ru: "Разрывание Шибаквы", en: "Xibaquas Rending", kind: 'support' },
  { ru: "Разряд", en: "Volt", kind: 'support' },
  { ru: "Разряд стихий", en: "Elemental Discharge", kind: 'support' },
  { ru: "Разъярение I", en: "Rageforged I", kind: 'support' },
  { ru: "Разъярение II", en: "Rageforged II", kind: 'support' },
  { ru: "Расплата Ромиры", en: "Romiras Requital", kind: 'support' },
  { ru: "Расправа", en: "Execrate", kind: 'support' },
  { ru: "Рассечение", en: "Excise", kind: 'support' },
  { ru: "Расцвет порчи", en: "Hex Bloom", kind: 'support' },
  { ru: "Расширение", en: "Expand", kind: 'support' },
  { ru: "Расщепляющийся тотем I", en: "Splinter Totem I", kind: 'support' },
  { ru: "Расщепляющийся тотем II", en: "Splinter Totem II", kind: 'support' },
  { ru: "Реверберация", en: "Reverberate", kind: 'support' },
  { ru: "Рефрен Зарока", en: "Zarokhs Refrain", kind: 'support' },
  { ru: "Решимость Гарухан", en: "Garukhans Resolve", kind: 'support' },
  { ru: "Ржавые шипы", en: "Rusted Spikes", kind: 'support' },
  { ru: "Рикошет I", en: "Ricochet I", kind: 'support' },
  { ru: "Рикошет II", en: "Ricochet II", kind: 'support' },
  { ru: "Рикошет III", en: "Ricochet III", kind: 'support' },
  { ru: "Ритм", en: "Cadence", kind: 'support' },
  { ru: "Ритм Тасалио", en: "Tasalios Rhythm", kind: 'support' },
  { ru: "Ритуал Утреда", en: "Uhtreds Rite", kind: 'support' },
  { ru: "Ритуал Эйнара", en: "Einhars Beastrite", kind: 'support' },
  { ru: "Ритуальное проклятие", en: "Ritualistic Curse", kind: 'support' },
  { ru: "Рунное извлечение", en: "Runic Extraction", kind: 'support' },
  { ru: "Рунное насыщение", en: "Runic Infusion", kind: 'support' },
  { ru: "Руннокованые клинки", en: "Runeforged Blades", kind: 'support' },
  { ru: "Сборище", en: "Muster", kind: 'support' },
  { ru: "Сверхкритический удар", en: "Supercritical", kind: 'support' },
  { ru: "Свирепость Ригвальда", en: "Rigwalds Ferocity", kind: 'support' },
  { ru: "Свирепость Стирна", en: "Styrns Ferocity", kind: 'support' },
  { ru: "Свирепость I", en: "Rage I", kind: 'support' },
  { ru: "Свирепость II", en: "Rage II", kind: 'support' },
  { ru: "Свирепость III", en: "Rage III", kind: 'support' },
  { ru: "Свирепый клич", en: "Raging Cry", kind: 'support' },
  { ru: "Священное сошествие", en: "Holy Descent", kind: 'support' },
  { ru: "Сердце серафима", en: "Seraphs Heart", kind: 'support' },
  { ru: "Сизигия", en: "Syzygy", kind: 'support' },
  { ru: "Сила замедления", en: "Slow Potency", kind: 'support' },
  { ru: "Сила сгустков I", en: "Remnant Potency I", kind: 'support' },
  { ru: "Сила сгустков II", en: "Remnant Potency II", kind: 'support' },
  { ru: "Сильная восприимчивость", en: "Potent Exposure", kind: 'support' },
  { ru: "Сияние Иш", en: "Eshs Radiance", kind: 'support' },
  { ru: "Скачущее напряжение", en: "Coursing Current", kind: 'support' },
  { ru: "Скованность", en: "Hinder", kind: 'support' },
  { ru: "Слияние Повелителя Разлома", en: "Breachlords Amalgam", kind: 'support' },
  { ru: "Сменный магазин I", en: "Fresh Clip I", kind: 'support' },
  { ru: "Сменный магазин II", en: "Fresh Clip II", kind: 'support' },
  { ru: "Смертельный яд I", en: "Deadly Poison I", kind: 'support' },
  { ru: "Смертельный яд II", en: "Deadly Poison II", kind: 'support' },
  { ru: "Смертоносная решимость", en: "Deadly Resolve", kind: 'support' },
  { ru: "Смертоносный вестник", en: "Deadly Herald", kind: 'support' },
  { ru: "Смятение", en: "Tumult", kind: 'support' },
  { ru: "Совершенство", en: "Perfection", kind: 'support' },
  { ru: "Содранная кожа", en: "Excoriate", kind: 'support' },
  { ru: "Созвездие Утреда", en: "Uhtreds Constellation", kind: 'support' },
  { ru: "Сокращение длительности I", en: "Compressed Duration I", kind: 'support' },
  { ru: "Сокращение длительности II", en: "Compressed Duration II", kind: 'support' },
  { ru: "Сонаправленность I", en: "Alignment I", kind: 'support' },
  { ru: "Сонаправленность II", en: "Alignment II", kind: 'support' },
  { ru: "Сонаправленность III", en: "Alignment III", kind: 'support' },
  { ru: "Сострадание", en: "Commiserate", kind: 'support' },
  { ru: "Сосулька", en: "Icicle", kind: 'support' },
  { ru: "Сотрясающие руны", en: "Concussive Runes", kind: 'support' },
  { ru: "Сотрясающие чары", en: "Concussive Spells", kind: 'support' },
  { ru: "Сохранение боеприпаса I", en: "Ammo Conservation I", kind: 'support' },
  { ru: "Сохранение боеприпаса II", en: "Ammo Conservation II", kind: 'support' },
  { ru: "Сохранение боеприпаса III", en: "Ammo Conservation III", kind: 'support' },
  { ru: "Сохранение трупов", en: "Corpse Conservation", kind: 'support' },
  { ru: "Сохранение энергии", en: "Energy Retention", kind: 'support' },
  { ru: "Спарринг", en: "Spar", kind: 'support' },
  { ru: "Спешные тотемы I", en: "Urgent Totems I", kind: 'support' },
  { ru: "Спешные тотемы II", en: "Urgent Totems II", kind: 'support' },
  { ru: "Спешные тотемы III", en: "Urgent Totems III", kind: 'support' },
  { ru: "Средоточие", en: "Concentrated Area", kind: 'support' },
  { ru: "Статический шок", en: "Static Shocks", kind: 'support' },
  { ru: "Стихийное войско", en: "Elemental Army", kind: 'support' },
  { ru: "Стихийное оружие I", en: "Elemental Armament I", kind: 'support' },
  { ru: "Стихийное оружие II", en: "Elemental Armament II", kind: 'support' },
  { ru: "Стихийное оружие III", en: "Elemental Armament III", kind: 'support' },
  { ru: "Стоицизм I", en: "Stoicism I", kind: 'support' },
  { ru: "Стоицизм II", en: "Stoicism II", kind: 'support' },
  { ru: "Столп огня", en: "Flame Pillar", kind: 'support' },
  { ru: "Страсть Дарессо", en: "Daressos Passion", kind: 'support' },
  { ru: "Стремительный недуг I", en: "Swift Affliction I", kind: 'support' },
  { ru: "Стремительный недуг II", en: "Swift Affliction II", kind: 'support' },
  { ru: "Стремительный недуг III", en: "Swift Affliction III", kind: 'support' },
  { ru: "Стреноживание", en: "Hobble", kind: 'support' },
  { ru: "Стужа", en: "Rime", kind: 'support' },
  { ru: "Стычка", en: "Clash", kind: 'support' },
  { ru: "Тектонические удары", en: "Tectonic Slams", kind: 'support' },
  { ru: "Теплокровность", en: "Warm Blooded", kind: 'support' },
  { ru: "Терновник", en: "Brambleslam", kind: 'support' },
  { ru: "Топотун", en: "Stomping Ground", kind: 'support' },
  { ru: "Точечные критические удары", en: "Pinpoint Critical", kind: 'support' },
  { ru: "Точность I", en: "Precision I", kind: 'support' },
  { ru: "Точность II", en: "Precision II", kind: 'support' },
  { ru: "Травничество I", en: "Herbalism I", kind: 'support' },
  { ru: "Травничество II", en: "Herbalism II", kind: 'support' },
  { ru: "Тяжёлый замах", en: "Heavy Swing", kind: 'support' },
  { ru: "Тяжесть", en: "Heft", kind: 'support' },
  { ru: "Убеждённость Олрота", en: "Olroths Conviction", kind: 'support' },
  { ru: "Увеличенная область I", en: "Magnified Area I", kind: 'support' },
  { ru: "Увеличенная область II", en: "Magnified Area II", kind: 'support' },
  { ru: "Увечье", en: "Maim", kind: 'support' },
  { ru: "Удар врасплох", en: "Blindside", kind: 'support' },
  { ru: "Удар по площади приспешников I", en: "Minion Splash I", kind: 'support' },
  { ru: "Удар по площади приспешников II", en: "Minion Splash II", kind: 'support' },
  { ru: "Удар с разбега", en: "Hit and Run", kind: 'support' },
  { ru: "Ударная волна", en: "Impact Shockwave", kind: 'support' },
  { ru: "Укреплённые тотемы I", en: "Reinforced Totems I", kind: 'support' },
  { ru: "Укреплённые тотемы II", en: "Reinforced Totems II", kind: 'support' },
  { ru: "Укус льда I", en: "Ice Bite I", kind: 'support' },
  { ru: "Укус льда II", en: "Ice Bite II", kind: 'support' },
  { ru: "Умение Иш", en: "Eshs Prowess", kind: 'support' },
  { ru: "Умышленное убийство", en: "Murderous Intent", kind: 'support' },
  { ru: "Управляемые помехи", en: "Controlled Hazard", kind: 'support' },
  { ru: "Ускорение перезарядки I", en: "Cooldown Recovery I", kind: 'support' },
  { ru: "Ускорение перезарядки II", en: "Cooldown Recovery II", kind: 'support' },
  { ru: "Ускорение cнарядов I", en: "Projectile Acceleration I", kind: 'support' },
  { ru: "Ускорение cнарядов II", en: "Projectile Acceleration II", kind: 'support' },
  { ru: "Ускорение cнарядов III", en: "Projectile Acceleration III", kind: 'support' },
  { ru: "Ускоренный рост", en: "Accelerated Growth", kind: 'support' },
  { ru: "Ускоренный рост II", en: "Accelerated Growth II", kind: 'support' },
  { ru: "Устойчивость I", en: "Steadfast I", kind: 'support' },
  { ru: "Устойчивость II", en: "Steadfast II", kind: 'support' },
  { ru: "Финальный удар I", en: "Combo Finisher I", kind: 'support' },
  { ru: "Финальный удар II", en: "Combo Finisher II", kind: 'support' },
  { ru: "Хаотичная заморозка", en: "Chaotic Freeze", kind: 'support' },
  { ru: "Хватка Владыки", en: "Dominus Grasp", kind: 'support' },
  { ru: "Хворь", en: "Malady", kind: 'support' },
  { ru: "Хладнокровие", en: "Cool Headed", kind: 'support' },
  { ru: "Ходячий камень I", en: "Skittering Stone I", kind: 'support' },
  { ru: "Ходячий камень II", en: "Skittering Stone II", kind: 'support' },
  { ru: "Хрупкая броня", en: "Brittle Armour", kind: 'support' },
  { ru: "Целеустремлённость", en: "Deliberation", kind: 'support' },
  { ru: "Цепь I", en: "Chain I", kind: 'support' },
  { ru: "Цепь II", en: "Chain II", kind: 'support' },
  { ru: "Цепь III", en: "Chain III", kind: 'support' },
  { ru: "Цитадель Ахна", en: "Ahns Citadel", kind: 'support' },
  { ru: "Шальные осколки I", en: "Wildshards I", kind: 'support' },
  { ru: "Шальные осколки II", en: "Wildshards II", kind: 'support' },
  { ru: "Шальные приспешники", en: "Crazed Minions", kind: 'support' },
  { ru: "Шанс заморозить", en: "Chance to Freeze", kind: 'support' },
  { ru: "Шипастая кожа I", en: "Thornskin I", kind: 'support' },
  { ru: "Шипастая кожа II", en: "Thornskin II", kind: 'support' },
  { ru: "Широкий охват", en: "Expanse", kind: 'support' },
  { ru: "Шквал", en: "Salvo", kind: 'support' },
  { ru: "Шкура Хельбрима", en: "Helbryms Hide", kind: 'support' },
  { ru: "Шок", en: "Shock", kind: 'support' },
  { ru: "Шокирующий прыжок", en: "Shocking Leap", kind: 'support' },
  { ru: "Щедрость I", en: "Bounty I", kind: 'support' },
  { ru: "Щедрость II", en: "Bounty II", kind: 'support' },
  { ru: "Щедрый оберег", en: "Charm Bounty", kind: 'support' },
  { ru: "Электризация", en: "Electrocute", kind: 'support' },
  { ru: "Электромагнетизм", en: "Electromagnetism", kind: 'support' },
  { ru: "Энергетический барьер", en: "Energy Barrier", kind: 'support' },
  { ru: "Эффективность I", en: "Efficiency I", kind: 'support' },
  { ru: "Эффективность II", en: "Efficiency II", kind: 'support' },
  { ru: "Эхо магии", en: "Spell Echo", kind: 'support' },
  { ru: "Ядовитые споры", en: "Poison Spores", kind: 'support' },
  { ru: "Яростное парирование", en: "Frenzied Riposte", kind: 'support' },
  { ru: "Яростный крик I", en: "Enraged Warcry I", kind: 'support' },
  { ru: "Яростный крик II", en: "Enraged Warcry II", kind: 'support' },
  { ru: "Ясность ума I", en: "Clarity I", kind: 'support' },
  { ru: "Ясность ума II", en: "Clarity II", kind: 'support' },
];
