/**
 * Карта наличия вояпоинта в зонах кампании (Акт 1–4).
 * Сгенерировано экстрактором _extract_waypoints.mjs из
 * repoe-fork world_areas.json (patch 0.5.5). Ключи — точные имена зон из leveling.ts.
 * Значение true = в зоне есть вояпоинт (быстрый телепорт).
 */
export const CAMPAIGN_WAYPOINTS: Record<string, boolean> = {
  'The Riverbank': false,
  'Clearfell': true,
  'Mud Burrow': false,
  'The Grelwood': true,
  'The Red Vale': true,
  'The Grim Tangle': true,
  'Cemetery of the Eternals': true,
  'Mausoleum of the Praetor': true,
  'Tomb of the Consort': true,
  'Hunting Grounds': true,
  'Freythorn': true,
  'Ogham Farmlands': true,
  'Ogham Village': true,
  'The Manor Ramparts': true,
  'Ogham Manor': true,
  'Vastiri Outskirts': true,
  'Traitor\'s Passage': true,
  'The Halani Gates': true,
  'Keth': true,
  'The Lost City': true,
  'Buried Shrines': true,
  'Mastodon Badlands': true,
  'Lightless Passage': true,
  'The Bone Pits': true,
  'Valley of the Titans': true,
  'The Titan Grotto': true,
  'Deshar': true,
  'Path of Mourning': true,
  'The Spires of Deshar': true,
  'Mawdun Quarry': true,
  'Mawdun Mine': true,
  'The Dreadnought': true,
  'Dreadnought Vanguard': true,
  'Sandswept Marsh': true,
  'Jungle Ruins': true,
  'Infested Barrens': true,
  'The Venom Crypts': true,
  'Chimeral Wetlands': true,
  'The Azak Bog': true,
  'Jiquani\'s Machinarium': true,
  'Jiquani\'s Sanctum': true,
  'The Matlan Waterways': true,
  'The Drowned City': true,
  'Apex of Filth': true,
  'Temple of Kopec': false,
  'Utzaal': true,
  'Aggorat': true,
  'The Black Chambers': true,
  'Isle of Kin': true,
  'Volcanic Warrens': true,
  'Kedge Bay': true,
  'Journey\'s End': true,
  'Whakapanu Island': true,
  'Singing Caverns': true,
  'Eye of Hinekora': true,
  'Halls of the Dead': true,
  'Trial of the Ancestors': true,
  'Abandoned Prison': true,
  'Solitary Confinement': true,
  'Shrike Island': true,
  'Arastas': true,
  'The Excavation': true,
  'Ngakanu': true,
  'Heart of the Tribe': true,
  'Plunder\'s Point': true,
};
